# Generated by Django 3.2.25 on 2024-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station', models.CharField(max_length=100)),
                ('end_station', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('available_seats', models.IntegerField()),
                ('total_passengers', models.IntegerField()),
                ('total_duration', models.CharField(default='Journey Ongoing!', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('onboard_frequency', models.IntegerField()),
                ('offboard_frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('onboard_frequency', models.IntegerField()),
                ('offboard_frequency', models.IntegerField()),
            ],
        ),
    ]
